/* Concept cards for Focused Study "learn before drilling".
   Each card: title, principle, method steps, one tiny worked example.
   TOPIC_CONCEPT maps every question topic to a concept key. */
const CONCEPTS = {
  "ratios":{title:"Ratios",principle:"A ratio cuts a total into equal 'parts'. Find the value of ONE part first, then multiply.",
    steps:["Add the ratio numbers to get the total number of parts.","Find one part: total ÷ parts, or (a given difference) ÷ (difference in parts).","Multiply one part by the number of parts each share needs."],
    example:"Share $180 as 1:3:5 → 9 parts, so 1 part = $20, and the shares are $20, $60, $100."},
  "fractions-of-quantity":{title:"Fractions of a quantity",principle:"'Of' means multiply. To find the whole from a part, set the known amount equal to its fraction of the whole, then scale up.",
    steps:["Track what fraction is left or spent at each step.","Combine steps by multiplying fractions (e.g. 3/4 of 2/3 = 1/2).","Put the known amount equal to its fraction of the whole, then find the whole."],
    example:"Spent 1/3, then 1/4 of the rest; $18 left = 1/2 of the start → start = $36."},
  "rates":{title:"Rates & proportion",principle:"Find the value of ONE unit (one litre, minute, dollar, person), then scale up or down.",
    steps:["Divide to get the 'per one' rate (e.g. km per litre).","Multiply that rate by the new amount you want.","For 'best value', compare the SAME per-unit measure for each option."],
    example:"240 km on 20 L → 12 km per litre, so 35 L → 35 × 12 = 420 km."},
  "unit-conversion":{title:"Unit conversion",principle:"Change everything to the same unit before calculating. Know the ladders: km–m–cm–mm, L–mL, h–min–s.",
    steps:["Decide the single unit you want to work in.","Multiply or divide by the conversion factor (×1000, ×60, …).","Do the sum, then convert the answer to the unit asked for."],
    example:"72 km/h = 72000 m ÷ 3600 s = 20 m/s, so in 45 s it travels 900 m."},
  "number-patterns":{title:"Number patterns",principle:"Find the RULE first by looking at the differences between terms.",
    steps:["Write the gaps between consecutive terms.","Equal gaps = a constant step; growing gaps = look at the second differences.","Extend the pattern, or find a formula using the position number n."],
    example:"2,5,10,17,26 → gaps 3,5,7,9; each term is n×n+1, so the 7th = 50."},
  "working-backwards":{title:"Working backwards",principle:"Start from the final result and UNDO each step in reverse, swapping every operation for its opposite.",
    steps:["Write the operations in the order they happened.","Start at the final number.","Reverse from last to first: + becomes −, × becomes ÷, and so on."],
    example:"×2, −5, ÷3 gives 7 → undo: 7×3 = 21, +5 = 26, ÷2 = 13."},
  "divisibility":{title:"Divisibility & digit puzzles",principle:"Use divisibility tests instead of trial and error.",
    steps:["÷2 even; ÷3 digit-sum ÷3; ÷4 last two digits ÷4; ÷5 ends 0/5; ÷9 digit-sum ÷9.","Apply each required test to narrow the digit choices.","Combine the conditions to find the only value that fits."],
    example:"4_6 divisible by 3 and 4 → middle digit must be odd (for ÷4) and make the sum ÷3 → 5 (456)."},
  "simple-algebra":{title:"Turning words into an equation",principle:"Let a letter stand for the unknown, translate the words into an equation, then solve.",
    steps:["Choose a letter for the unknown (often the smaller/base quantity).","Write the other quantities in terms of that letter.","Form the equation from the total and solve, then check in the words."],
    example:"Pen = pencil + $2; 3 pencils + 2 pens = $19 → 5p + 4 = 19, p = 3, pen = $5."},
  "area":{title:"Area (composite & scale)",principle:"Break an odd shape into rectangles, or subtract a missing piece from a big rectangle.",
    steps:["Split the shape into rectangles, or find the surrounding rectangle and the cut-out.","Work out each area (length × width).","Add the pieces, or subtract the cut-out. With a map scale, convert each side to real length BEFORE multiplying."],
    example:"A 15×10 rectangle with a 9×4 bite removed → 150 − 36 = 114 m²."},
  "perimeter":{title:"Perimeter",principle:"Perimeter is the distance all the way around — add every side, working out any missing ones.",
    steps:["Mark every side; find missing sides using opposite sides.","On a staircase edge, the horizontal steps add up to the full width and the vertical steps to the full height.","Add all the way around."],
    example:"Staircase (12 across, 9 up) + a 12 bottom + a 9 side → 21 + 12 + 9 = 42 cm."},
  "volume":{title:"Volume & capacity",principle:"Box volume = length × width × height; 1000 cm³ = 1 litre. A submerged object raises the water by its own volume.",
    steps:["Multiply the three dimensions for a box.","Convert cm³ ↔ litres if needed (÷1000).","Filling with a leak: use the NET rate (in − out). Submerged object: volume = base area × rise in level."],
    example:"Water rising 4 cm over a 40×25 base → 1000 × 4 = 4000 cm³ of rock."},
  "surface-area":{title:"Surface area",principle:"Surface area = the areas of ALL the faces added together.",
    steps:["Work out the size of each face.","A box has 3 pairs of matching faces — find each pair once and double it.","Add all the faces together."],
    example:"Square base 5×5 (×2 = 50) + four 5×8 sides (= 160) → 210 cm²."},
  "angles":{title:"Angles",principle:"Angles in a triangle add to 180°, on a straight line to 180°, around a point to 360°; a polygon's exterior angles add to 360°.",
    steps:["Decide which rule applies (triangle, straight line, polygon).","Write the angles as parts or as an equation.","Solve — remember an isosceles triangle has two equal angles."],
    example:"Angles in ratio 2:3:4 → 9 parts, one part = 20°, so 40°, 60°, 80°."},
  "clock-angles":{title:"Clock angles",principle:"The minute hand moves 6° per minute; the hour hand moves 30° per hour PLUS 0.5° per minute.",
    steps:["Minute-hand angle = minutes × 6.","Hour-hand angle = hours × 30 + minutes × 0.5.","Subtract the two to get the angle between them."],
    example:"At 3:40 → minute hand 240°, hour hand 110°, difference = 130°."},
  "elapsed-time":{title:"Elapsed & calendar time",principle:"Count on in chunks (whole hours, then minutes); watch am/pm, dates and time zones.",
    steps:["Add the hours first, then the minutes; watch for crossing 12 or midnight.","For a duration, subtract the start from the end.","For calendars, count the days then use the ÷7 remainder for the weekday. Adjust a time zone by adding/subtracting the difference."],
    example:"11:45 pm + 14 h 30 min = 2:15 pm next day; a zone 5 h behind → 9:15 am."},
  "transformations":{title:"Transformations (coordinates)",principle:"Reflections flip a sign; rotations swap/relabel the coordinates. Do the steps in the given order.",
    steps:["Reflect in the y-axis: (x,y)→(−x,y); in the x-axis: (x,y)→(x,−y).","Rotate 90° clockwise about O: (x,y)→(y,−x); anticlockwise: (x,y)→(−y,x).","Apply one transformation at a time, in order."],
    example:"(3,1) reflected in the y-axis → (−3,1); rotated 90° clockwise → (1,3)."},
  "symmetry":{title:"Symmetry & folding",principle:"Rotational symmetry: it looks the same when turned. Folding DOUBLES the layers each fold.",
    steps:["For half-turn symmetry, imagine turning the shape 180° — does it match?","For folding, each fold doubles the layers (2, 4, 8, …).","One punch makes one hole per layer."],
    example:"3 folds = 8 layers, so a single punch → 8 holes."},
  "spatial-3d":{title:"3-D & spatial reasoning",principle:"Picture the solid, count carefully, and watch for shared or overlapping cubes.",
    steps:["Painted cube: corners have 3 painted faces, edges 2, face-centres 1, inside 0.","For a net, pick one face as 'front' and fold the neighbours around it.","For drilled tunnels, subtract shared cubes so the centre isn't counted twice."],
    example:"3×3×3 cube with 3 tunnels through the centre → 1 centre + 6 arms = 7 cubes removed."},
  "mean":{title:"Mean (average) problems",principle:"TOTAL = mean × count. Almost every average puzzle is solved through the total.",
    steps:["Turn each average into a total (mean × how many).","Add or remove the given values, adjusting the total.","Divide the new total by the new count, or solve for the missing value."],
    example:"6 numbers, mean 15 → total 90; remove one, 5 left with mean 13 → total 65; removed = 25."},
  "mean-median-mode":{title:"Mean, median & mode together",principle:"Median = the middle value (sort first!); mode = the most common; mean = total ÷ count. Use each clue to pin the numbers.",
    steps:["Sort the numbers; the median is the middle one (or the average of the two middle).","The mode tells you which value repeats.","Use total = mean × count to find what is left; check every clue fits."],
    example:"5 numbers: mode 4 (twice), median 5, mean 6 (total 30) → 4, 4, 5, 6, 11."},
  "probability-basic":{title:"Basic probability",principle:"Probability = favourable outcomes ÷ total outcomes. 'Not' = 1 − P. Independent events multiply.",
    steps:["Count the total possible outcomes.","Count the ones you want.","For 'not', subtract from 1; for 'A and B' (independent), multiply the two probabilities."],
    example:"P(heads and an even number) = 1/2 × 1/2 = 1/4."},
  "probability-combined":{title:"Combined probability",principle:"Multiply along a path of steps; for 'without replacement' the totals shrink; add the different paths for 'or'.",
    steps:["Find the probability of each step.","'Without replacement': reduce the counts after each draw.","Multiply along one path; add paths that both count (e.g. red-then-blue AND blue-then-red). 'At least one' is often easier as 1 − P(none)."],
    example:"Two black from 3 black, 2 white → 3/5 × 2/4 = 3/10."},
  "probability-sets":{title:"Probability with overlapping groups",principle:"When groups overlap, count 'at least one' = A + B − both, then divide.",
    steps:["Find how many are in at least one group (A + B − both).","Pick the count the question asks about.","Divide by the correct total (usually 'at least one')."],
    example:"Soccer 12, tennis 8, both 5 → at least one = 15; P(plays tennis) = 8/15."},
  "counting":{title:"Systematic counting",principle:"Count in an organised way — list, or multiply the choices — so nothing is missed or repeated.",
    steps:["Decide the number of choices for each position (and whether repeats are allowed).","Multiply the choices (e.g. 4 × 3 for two different digits).","If order does NOT matter (pairs, handshakes), divide by 2. For 'ways to make an amount', list by the number of the biggest coin."],
    example:"Handshakes among 6 people = 6 × 5 ÷ 2 = 15."},
  "venn":{title:"Venn / set overlaps",principle:"Never double-count the overlap. Two sets: A + B − both = at least one. Three sets use inclusion–exclusion.",
    steps:["Two sets: (at least one) = A + B − both; add the 'neither' group for the grand total.","Three sets: singles − pairs + all-three = at least one.","Draw the diagram and fill the middle (all-three) first if you can."],
    example:"40 people: coffee 25, tea 20, neither 8 → at least one = 32 → both = 25 + 20 − 32 = 13."},
  "age-problems":{title:"Age problems",principle:"Write both ages now with a letter, then add/subtract the SAME number of years to BOTH for another time.",
    steps:["Let the unknown age be a letter; write the other age in terms of it.","'In n years' add n to both; 'n years ago' subtract n from both.","Form the equation from the relationship, solve, and check both times."],
    example:"Mum = 4 × daughter; in 5 years 4d + 5 = 3(d + 5) → d = 10."},
  "coins":{title:"Coin & money combinations",principle:"Two facts — how many coins and the total value — give two equations you solve together.",
    steps:["Let each coin count be a letter.","Write one equation for the number of coins and one for the total value (in cents).","Subtract or substitute to solve, then check the value adds up."],
    example:"20 coins of 10c and 20c worth $3.10 → 11 twenty-cent + 9 ten-cent coins."},
  "distance-rate-time":{title:"Distance, speed & time",principle:"distance = speed × time. Average speed = TOTAL distance ÷ TOTAL time (never just average the speeds).",
    steps:["Use d = s × t, rearranged for what you need.","Approaching each other: ADD the speeds; catching up: SUBTRACT the speeds.","For average speed, find total distance and total time separately, then divide."],
    example:"100 km at 50 then 100 km at 100 → 200 km in 3 h = 66⅔ km/h."},
  "logic":{title:"Logic deduction",principle:"Turn each clue into an ordering or a fact, then combine them into one chain.",
    steps:["Write each clue as 'before/after' or 'higher/lower'.","Chain the clues together into one full order.","For 'all labels wrong' puzzles, one certain fact fixes all the rest."],
    example:"Dan > Amy > Ben, and Cara after Ben → Dan, Amy, Ben, Cara; Cara is last."},
  "data-read":{title:"Reading tables & graphs",principle:"Read the exact row/column first, then do the calculation the question actually asks.",
    steps:["Find the precise value(s) — check both the row and column headings.","Do the operation asked (difference, fraction, percentage, mean).","'Percentage points' = subtract the two percentages, not the raw numbers. Re-check you used the right total."],
    example:"Cats: 15 + 20 = 35; Year 6 cats = 20 → fraction 20/35 = 4/7."},
  "data-money":{title:"Price lists, deals & timetables",principle:"Work out each part, apply any special condition, then total; compare deals by their real cost.",
    steps:["Multiply each item by its quantity or price.","Apply conditions exactly (discount only if buying 4+, family pass vs singles, etc.).","For timetables, find durations by counting on; add wait times only if asked.","Add up, then answer the exact question (total, change, or cheapest)."],
    example:"5 pens −10% + 3 notebooks (no discount) + 4 highlighters −10% = $29.73."}
};
const TOPIC_CONCEPT = {
  "ratios":"ratios",
  "fractions of quantities":"fractions-of-quantity",
  "rates":"rates","proportion":"rates","recipe scaling":"rates","best value / unit rate":"rates","conversion":"rates",
  "unit conversion":"unit-conversion","unit conversion and speed":"unit-conversion",
  "number patterns":"number-patterns","pattern recognition sequences":"number-patterns",
  "working backwards":"working-backwards",
  "divisibility and digit puzzles":"divisibility",
  "simple algebra":"simple-algebra",
  "composite area":"area","scale and area":"area",
  "composite perimeter":"perimeter",
  "volume":"volume","volume and capacity":"volume","capacity and rate":"volume",
  "volume and surface area":"surface-area",
  "angles":"angles","polygon angles":"angles",
  "clock angles":"clock-angles",
  "elapsed time":"elapsed-time","calendar time":"elapsed-time","timetable":"elapsed-time",
  "transformations":"transformations",
  "rotational symmetry":"symmetry","folding and symmetry":"symmetry",
  "cube counting":"spatial-3d","nets of a cube":"spatial-3d","cross-sections":"spatial-3d","spatial reasoning":"spatial-3d",
  "averages backwards":"mean","effect of adding a value on the mean":"mean","weighted mean of two groups":"mean","mean comparison":"mean","what-if inference":"mean",
  "median and mean combined":"mean-median-mode","median with even count":"mean-median-mode","mode and mean combined":"mean-median-mode","mode, median and mean combined":"mean-median-mode","effect of changing a value":"mean-median-mode",
  "single-event probability":"probability-basic","comparing likelihoods":"probability-basic","combined independent events":"probability-basic",
  "combined events":"probability-combined","probability without replacement":"probability-combined",
  "probability from overlapping sets":"probability-sets",
  "systematic counting":"counting","systematic counting with a constraint":"counting","systematic listing/counting":"counting","combinations":"counting",
  "venn 2 sets":"venn","venn 3 sets":"venn",
  "age problem":"age-problems",
  "coin/money combinations":"coins",
  "distance-rate-time":"distance-rate-time",
  "logic deduction":"logic",
  "two-way table":"data-read","table of values":"data-read","bar/column data":"data-read","bar data with missing category":"data-read","two-group comparison":"data-read","line/trend data":"data-read","percentage points":"data-read",
  "price list / menu":"data-money","deal comparison":"data-money","conditional discount":"data-money","shift hours":"data-money"
};
if (typeof module !== "undefined") { module.exports = { CONCEPTS, TOPIC_CONCEPT }; }
